### ISSUE TITLE
UnicodeDecodeError when running setup.py

### ISSUE THREAD

**Issue by Trasp** [ITCase/sqlalchemy_mptt#44]
I'm getting this UnicodeDecodeError when trying to run setup.py (with or without pip).
```
Traceback (most recent call last):
 File "setup.py", line 7, in <module>
    __version__ = (re.search(r'__version__\s*=\s*u?"([^"]+)"', fh.read())
 File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
     return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 78: ordinal not in range(128)
```

**Comment by uralbash** [comment]
I updated version on PyPi to 0.1.6.post1.
